### ISSUE TITLE
Some problems with the runtime of the code

### ISSUE THREAD

**Issue by Qinulinuli** [BojarLab/glycowork#21]
Dear Glycowork

When I tried to run example of Constructing and exploring biosynthetic networks, plot_network gave the following error message：

![代码问题](https://user-images.githubusercontent.com/116611946/197709200-a4ba6ce3-faeb-49fe-8ab9-6dde5e4db118.png)

Would you please help me solve this problem?

kind regards,

Qi

**Comment by Bribak** [comment]
Hi Qi,

thanks for your interest in glycowork!
I'll likely need some more information what code you ran in order to help you.

I do note however that the network module was built and optimized in a Jupyter notebook environment, so it could be that mpld3 does not like a non-notebook environment. This would only affect plot_network and is used to enable display of node label by hovering the cursor over the node. You can test this by running nx.draw(network) & displaying it via plt.show() ; this should show your network (but without the functionality of mpld3).
I can look into modifying it for the upcoming version update but the most likely change will be that we'll make plot_network detect the environment and only do the fancy plotting in a suitable environment, so I'd anyways recommend two options:
1) plot the network in a notebook environment
or 2) use export_network to modify the network visuals in a program of your choice.

All the best,
Daniel

**Comment by Bribak** [comment]
Update: I looked into this and it's indeed mpld3 in a non-notebook environment. I've added a failsafe on the dev branch (728ada6ba8c37ad0aa1fc4fea7f5efb041d92fed), so that the function will not return an error in other environments. However, that also means that the functionality provided by mpld3 cannot be utilized, so the resulting plot will be a bit lackluster (i.e., I'd always recommend notebooks for plotting networks until someone has implemented an mpld3-free workflow for this:-) ).

We'll anyways do a version update soon-ish, so if you do not want to use the dev-branch version, I'd recommend you do the other two suggestions from above until the version is updated.

I'll close this for now, but feel free to open another issue if you encounter something different.
Thanks so much for bringing this to our attention!

**Comment by Qinulinuli** [comment]
Hi Daniel，
Thank you very much for your help and quick reply!
Changed according to the dev branch (https://github.com/BojarLab/glycowork/commit/728ada6ba8c37ad0aa1fc4fea7f5efb041d92fed) , I successfully run nx.draw(network) & display via plt.show() to show the network.
