### ISSUE TITLE
Wrong orientation of core-fucoses in `GlycoDraw`.

### ISSUE THREAD

**Issue by fubin1999** [BojarLab/glycowork#45]
Hi! Thanks for developing this wonderful package. The `GlycoDraw` function produces really modern, publish-ready SNFG cartoons.

I've found some bugs though:

1. `GlycoDraw` may output empty SVG files when `vertical` setting to True.
2. The orientation of the core-fucose is unorthodox. For example, `GlycoDraw` draws a cartoon for "H4N3F1" as follows:

<img width="250" alt="截屏2024-06-03 14 57 41" src="https://github.com/BojarLab/glycowork/assets/65430559/c5d2cf87-167d-4a83-93e9-dcd130e36158">

However, the core-fucose is more often drawn in another orientation by the N-glycomics community:

<img width="250" alt="截屏2024-06-03 15 01 07" src="https://github.com/BojarLab/glycowork/assets/65430559/51fdfb94-3818-4ef7-b4f5-1d4689f65cb1">

**Comment by lundstrm** [comment]
Hi & thanks for the interest! 

1) This has been fixed with commit 5bee4d9 (already available on the dev branch and will be merged into main with the upcoming 1.3 update)
2) While we acknowledge that various tools may depict the core fucose in different orientations, we have decided to maintain the current behavior of GlycoDraw, as this approach is consistent with the examples provided on the SNFG website (https://www.ncbi.nlm.nih.gov/glycans/snfg.html, version 2.0.4).

**Comment by fubin1999** [comment]
I see. I'll go along with the NCBI example then. Thanks a lot!
